apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooppdfgen
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  leaderElection: false
  prometheus:
    path: /internal/prometheus
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    inbound:
      rules:
        - application: esyfovarsel
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: {{syfooppfolgingsplanservice_cluster}}
  ingresses:
    - {{ingress}}
