name: main

on: push

env:
  APP_NAME: syfooppdfgen
  IMAGE: docker.pkg.github.com/${{ github.repository }}/syfooppdfgen:${{ github.sha }}
  COMMITER_NAME: ${{ github.event.pusher.name }}

jobs:
  build:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          echo ${IMAGE}

  deploy-dev:
    if: github.ref == 'refs/heads/master'
    name: Deploy to NAIS Dev-fss
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator.yaml

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    name: Deploy to NAIS Prod-fss
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: naiserator.yaml

  pling:
    if: github.ref == 'refs/heads/master'
    name: Pling!
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - name: Pling
        run: |
          curl -s "https://syfoping.herokuapp.com/regDeploy?deployedBy=${COMMITER_NAME}&app=${APP_NAME}"

